version: '3.8'
services: 
  rct-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rct
    networks:
      - freecodecamp
networks:
  freecodecamp: