export enum Brand {
  ASUS = "ASUS",
  AMD = "AMD",
  GOOGLE = "GOOGLE",
  INTEL = "INTEL",
  MICROSOFT = "MICROSOFT",
  NVIDIA = "NVIDIA",
  COOLER_MASTER = "COOLER MASTER",
  KINGSTON = "KINGSTON",
  CORSAIR = "CORSAIR",
  PHANTEKS = "PHANTEKS",
  GIGABYTE = "GIGABYTE",
  NOX = "NOX",
  WESTERN_DIGITAL = "WESTERN DIGITAL",
  SAMSUNG = "SAMSUNG"
}